
export const FETCH_REVIEW_MAIN_FIRST_SUCCESS = 'FETCH_REVIEW_MAIN_FIRST_SUCCESS';
export const FETCH_REVIEW_MAIN_CONTINUE_SUCCESS = 'FETCH_REVIEW_MAIN_CONTINUE_SUCCESS';
export const FETCH_REVIEW_MAIN_LAST_SUCCESS = 'FETCH_REVIEW_MAIN_LAST_SUCCESS';
export const FETCH_REVIEW_MAIN_FAILURE = 'FETCH_REVIEW_MAIN_FAILURE';

export const POST_REVIEW_LIKE_SUCCESS = 'POST_REVIEW_LIKE_SUCCESS';
export const POST_REVIEW_LIKE_DUPLICATION = 'POST_REVIEW_LIKE_DUPLICATION';
export const POST_REVIEW_LIKE_FAILURE = 'POST_REVIEW_LIKE_FAILURE';

export const SELECT_REVIEW_FILTER_SUCCESS = 'SELECT_REVIEW_FILTER_SUCCESS';
export const SELECT_REVIEW_FILTER_FAILURE = 'SELECT_REVIEW_FILTER_FAILURE';


export const FETCH_WEBTOON_INFO_SUCCESS = 'FETCH_WEBTOON_INFO_SUCCESS';
export const FETCH_WEBTOON_INFO_FAILURE = 'FETCH_WEBTOON_INFO_FAILURE';

export const FETCH_REVIEW_DETAIL_FIRST_SUCCESS = 'FETCH_REVIEW_DETAIL_FIRST_SUCCESS';
export const FETCH_REVIEW_DETAIL_CONTINUE_SUCCESS = 'FETCH_REVIEW_DETAIL_CONTINUE_SUCCESS';
export const FETCH_REVIEW_DETAIL_LAST_SUCCESS = 'FETCH_REVIEW_DETAIL_LAST_SUCCESS';
export const FETCH_REVIEW_DETAIL_FAILURE = 'FETCH_REVIEW_DETAIL_FAILURE';

export const POST_BOOKMARK_SAVE_SUCCESS = 'POST_BOOKMARK_SAVE_SUCCESS';
export const POST_BOOKMARK_DELETE_SUCCESS = 'POST_BOOKMARK_DELETE_SUCCESS';
export const POST_BOOKMARK_FAILURE = 'POST_BOOKMARK_FAILURE';

export const FETCH_FILTER_TAG_SUCCESS = 'FETCH_FILTER_TAG_SUCCESS';
export const FETCH_FILTER_TAG_FAILURE = 'FETCH_FILTER_TAG_FAILURE';

export const READ_MORE_SUCCESS = 'READ_MORE_SUCCESS';
export const READ_MORE_FAILURE = 'READ_MORE_FAILURE';

export const FETCH_TOP_WEBTOON_SUCCESS = 'FETCH_TOP_WEBTOON_SUCCESS';
export const FETCH_TOP_WEBTOON_FAILURE = 'FETCH_TOP_WEBTOON_FAILURE';